export const WIDGET_PRESETS = [
    // 암호화폐 거래소 - 보안상 iframe 차단되므로 경고 표시용
    {
        id: "bithumb",
        name: "빗썸",
        url: "https://www.bithumb.com/",
        category: "crypto",
        icon: "Bitcoin",
        description: "빗썸 암호화폐 거래소 (보안상 차단될 수 있음)",
        type: "iframe",
    },
    {
        id: "upbit",
        name: "업비트",
        url: "https://upbit.com/",
        category: "crypto",
        icon: "Bitcoin",
        description: "업비트 암호화폐 거래소 (보안상 차단될 수 있음)",
        type: "iframe",
    },
    {
        id: "coinone",
        name: "코인원",
        url: "https://coinone.co.kr/",
        category: "crypto",
        icon: "Bitcoin",
        description: "코인원 암호화폐 거래소 (보안상 차단될 수 있음)",
        type: "iframe",
    },
    // TradingView 차트 - 공식 위젯 사용
    {
        id: "crypto-chart-btc",
        name: "비트코인 차트",
        category: "crypto",
        icon: "TrendingUp",
        description: "비트코인 실시간 차트",
        type: "tradingview",
        symbol: "UPBIT:BTCKRW",
    },
    {
        id: "crypto-chart-eth",
        name: "이더리움 차트",
        category: "crypto",
        icon: "TrendingUp",
        description: "이더리움 실시간 차트",
        type: "tradingview",
        symbol: "UPBIT:ETHKRW",
    },
    // 증권사 - 보안상 iframe 차단되므로 경고 표시용
    {
        id: "kiwoom",
        name: "키움증권",
        url: "https://www.kiwoom.com/",
        category: "stock",
        icon: "TrendingUp",
        description: "키움증권 홈트레이딩 (보안상 차단될 수 있음)",
        type: "iframe",
    },
    {
        id: "mirae",
        name: "미래에셋증권",
        url: "https://securities.miraeasset.com/",
        category: "stock",
        icon: "TrendingUp",
        description: "미래에셋증권 (보안상 차단될 수 있음)",
        type: "iframe",
    },
    {
        id: "samsung",
        name: "삼성증권",
        url: "https://www.samsungpop.com/",
        category: "stock",
        icon: "TrendingUp",
        description: "삼성증권 (보안상 차단될 수 있음)",
        type: "iframe",
    },
    {
        id: "kb",
        name: "KB증권",
        url: "https://www.kbsec.com/",
        category: "stock",
        icon: "TrendingUp",
        description: "KB증권 (보안상 차단될 수 있음)",
        type: "iframe",
    },
    {
        id: "naver-finance",
        name: "네이버 증권",
        url: "https://finance.naver.com/",
        category: "stock",
        icon: "BarChart3",
        description: "네이버 금융 - 주식 정보",
        type: "iframe",
    },
    {
        id: "stock-chart-kospi",
        name: "코스피 차트",
        category: "stock",
        icon: "TrendingUp",
        description: "코스피 실시간 차트",
        type: "tradingview",
        symbol: "KRX:KOSPI",
    },
    {
        id: "stock-chart-kosdaq",
        name: "코스닥 차트",
        category: "stock",
        icon: "TrendingUp",
        description: "코스닥 실시간 차트",
        type: "tradingview",
        symbol: "KRX:KOSDAQ",
    },
    // 금 시세
    {
        id: "gold-chart",
        name: "금 시세",
        category: "gold",
        icon: "Coins",
        description: "금 실시간 차트",
        type: "tradingview",
        symbol: "TVC:GOLD",
    },
    // 환율
    {
        id: "forex-usd",
        name: "달러/원 환율",
        category: "forex",
        icon: "DollarSign",
        description: "달러/원 환율 차트",
        type: "tradingview",
        symbol: "FX_IDC:KRWUSD",
    },
];
